### ISSUE TITLE
TODO Ticketing Team

### ISSUE THREAD

**Issue by ariestiyansyah** [id-python/pycon-2017#11]

**Comment by Keda87** [comment]
@rezhajulio persiapan

**Comment by RizRiyz** [comment]
@Keda87 @rezhajulio kita update di meeting Rabu, 11 Desembe 2017 ya untuk ticketing dan website.

**Comment by rezhajulio** [comment]
Setelah explore beberapa ticketing system, sepertinya akan menggunakan https://alf.io/ karena sudah cukup complete untuk cover pembayaran offline dan kartu kredit (via Stripe dan Paypal) serta memiliki mobile apps untuk [check in](https://alf.io/tutorials/check-in/).

![selection_148](https://cloud.githubusercontent.com/assets/10265290/21851126/48a37520-d840-11e6-95cb-ce2739304272.png)

**Comment by rezhajulio** [comment]
Alternatif lainnya menggunakan prismapp.io. Kalau menggunakan Prism tidak perlu lagi menggunakan ticketing platform, cukup membuat website Pycon dan menyematkan Prism di halamannya. Masih menunggu konfirmasi om Fauzan.
