### ISSUE TITLE
TODO Swag/Gear Team

### ISSUE THREAD

**Issue by ariestiyansyah** [id-python/pycon-2017#13]

**Comment by essanpupil** [comment]
Beberapa hari lalu saya tanya ke teman saya yang berbisnis sablon kaos dan stiker. Kisaran harga untuk pesan 200 kaos (sesuai target peserta PyConID 2017) adalah 50.000 per kaos. Harga masih bergantung pada desain, luas area sablon, dan harga bahan baku  (kemungkinan harga kaos). Sedangkan untuk stiker, harganya berkisar 25.000 per A3 + laminating (doff/glossy).

Sepertinya perlu diskusi tentang desainstiker dan desain kaos juga.
