### ISSUE TITLE
TODO Talk Program Team

### ISSUE THREAD

**Issue by ariestiyansyah** [id-python/pycon-2017#15]

**Comment by 3mp3ri0r** [comment]
@amryfitra, @edwinlunando, @ariestiyansyah (Bener kan ya Rizky ini Mas @ariestiyansyah). Hahaha. Akhirnya fokus materi kemana ya? Untuk pemula, menengah, atau advance? Target peserta mahasiswa atau siapa? Atau belum dibahas? *maklum, kemarin ga bisa ikut rapat. Hehehe.

**Comment by ir210** [comment]
Hi semua,

Enaknya bagaimana mulainya, ya?

Untuk fokus materi, menurut info @ariestiyansyah, lebih ditujukan untuk pemula Python. Mungkin yang sudah pernah ikut pycon, bisa ceritakan dulu seperti apa pembagian acaranya di pycon-pycon yang lain? Jadi semua punya gambaran mau dibuat seperti apa.

Common wisdom, sih, untuk awal kita contoh format yang sudah established. Baru mungkin kalau ada ide pengembangan bisa di-floor-kan kemudian.

**Comment by ir210** [comment]
Sesuai instruksi, fokus bulan ini adalah:
1. Rule untuk Call for Proposal
2. Estimasi budget.

**Comment by 3mp3ri0r** [comment]
Mas @arisbw sudah pengalaman jadi pembicara di pycon.

**Comment by ir210** [comment]
Sudah saya tanya. Saya lagi coba pelajari dari link yang dikasih, juga.

**Comment by RizRiyz** [comment]
@ir210 untuk pembagian acara di pycon yang pernah saya ikuti sederhana.

1. Keynote Speaker
2. Classroom : semua speaker dari CFP mengisi sesi mereka disini
3. Workshop

Untuk di Hongkong sendiri itu beda, mereka ada sprint sejalan dengan classroom jadi kalau ada yang mau bergabung untuk buat project langsung selama 2 hari tersebut without ikut classroom bisa ikut project sprint.

**Comment by 3mp3ri0r** [comment]
Bagus nih konsep yang di hongkong
