### ISSUE TITLE
Task November - December 2016 

### ISSUE THREAD

**Issue by ariestiyansyah** [id-python/pycon-2017#19]
- Sponsorships Team
    - Sponsorship Proposal
    - PSF Grants (Hampir semua PyCon disponsori oleh Python Software Foundation)
    - Buat estimasi budget untuk semua kebutuhan sponsorship
- Talk Program
    - Rule untuk CFP
    - Buat estimasi budget
- Food
    - Plan untuk Food
    - Buat estiasmi budget
- Swag Person
    - vendor untuk produksi swag
    - Buat estimasi budget
- Venue
    - Tentukan Lokasi acara dan hubungi kampus/institusi
    - Survery bila perlu
    - Buat estimasi budget
- Ticketing and Website
    - Define Platform ticketing
    - Buat Website pycon id 2017 
    - Buat estimasi budget
- Sprint Manager
    - Design ide sprint
    - Buat estimasi Budget
- External Liason
    - Check izin visa application untuk peserta
    - Buat estimasi budget
- Media
    - List Media di Indonesia
    - List Media Teknologi di Indonesia
    - Buat estimasi budget
- Financial Aid
    - Define Financial Aid Plan
    - Buat pengumuman untuk financial aid, kriteria untuk financial aid
    - Buat estimasi budget
- Designer
    - Logo untuk Pycon id
    - Poster
    - Buat estimasi budget
- Finance
    - Collect semua estimasi budget dan buat rencana anggaran pycon id 2017
- All Team
    - Set the date

**Comment by essanpupil** [comment]
[Swag] Kayaknya dari bagian Swag saya aja ya, nggak papa sih. Tapi masalahnya saya nggak bisa buat desain kaos yang bagus. Tolong donk team Desain sekalian buat desain untuk Swag.

Setelah saya tanya ke teman-teman saya di bisnis sticker & kaos, desain berpengaruh ke biaya. Kalau saya tanya perkiraan harga, mereka selalu menanyakan desain yg akan dicetak.

**Comment by nsiregar** [comment]
om @essanpupil boleh deh ane bantuin kalo diijinin

**Comment by essanpupil** [comment]
Wew, boleh banget @nsiregar, punya kenalan vendor percetakan kaos & sticker kah? Atau bisa desain sticker & kaos untuk pycon?
