### ISSUE TITLE
Panitia PyCon Indonesia

### ISSUE THREAD

**Issue by ariestiyansyah** [id-python/pycon-2017#2]
Roles untuk PyCon Indonesia 2017.
1. Sponsorships (Creates the sponsorship packages, finds sponsors and be the go-between between us and the sponsors.)
2. Talk program manager (decides what talks are received, goes where and when, controls Guidebook or whatever we use)  (**_Edwin, Amry, Christoforus, Irsyad_**)
3. Food manager (Snacks, Lunch and PyCon Dinner, coffee flow)
4. Swag person (manages tshirts and stickers production, also other stuff our sponsors give us) (**_Ikhsan_**)
5. Venue manager (Liaise with the venue and makes sure things are in place, we have stuff to use, banners, MCs, time keepers and also cleaning up) (**Alan Nugrohadi**)
6. Ticketing manager (manages the ticketing platform, and attendees list) (**_Rezha, Adit_**)
7. Sprints manager (Fixes sprints venue, leading developers and also schedule) (**_Fauzan_**)
8. External liason, outreach (Handles communication with external parties, visa applications for attendees and makes sure our VIPs are treated well) (**Vina**)
9. Media manager (Blog, twitter, FB, tie-up with local media, controls the website, live updates during conference) (**_Farah, Indra_**)
10. Financial aid (Sets the text for announcement, points criteria for selection, selects and works with Finance for the funds) (**_IsmailSunni_**)
11. Designer (Design the logos, tshirts, stickers and other stuff)(**_Ardo_**)
12. Finance (Sets the budget and makes sure we have cash flow) (**_IsmailSunni_**)
13. Co-chair (Helps everyone else) (**_Ikhsan_**)
14. Chair (Helps everyone else) (**_Rizky, Ikhsan_**)

Silahkan berikan komentar untuk role yang kalian inginkan dengan format:
nama: xxx
surel: xxx@xxx.xxx

Submission Deadline: 30 October 2016
Note: Dengan mendaftar menjadi panitia PyCon Anda berkomitmen untuk kontribusi sampai acara selesai, yeaaay!!!

**Comment by ismailsunni** [comment]
Nama: Ismail Sunni
surel: imajimatika@gmail.com

role: Financial aid atau Finance

**Comment by rezhajulio** [comment]
Nama: Rezha Julio
surel: contact [at] rezhajulio.web.id

role: Ticketing

**Comment by Keda87** [comment]
Ticketing.
Nama : Adit
Surel : adiyatmubarak@gmail.com

**Comment by 3mp3ri0r** [comment]
Talk program manager
Nama: Christoforus Surjoputro
Surel: christoforus.surjoputro@gmail.com

Note: posisi di Surabaya, jadi pilih yang bisa remote saja. Hehehe.

**Comment by amryamanah** [comment]
Tolong saya di remove dari Sponsorship yah. Terimakasih

**Comment by essanpupil** [comment]
Nama: Ikhsan Noor Rosyidin
Email: jakethitam1985@gmail.com
Tugas: Swag person (& pembantu umum)

**Comment by ir210** [comment]
Nama: Irsyad Asyhari Lubis
Email: irsyad.lubis@gmail.com
Role: Talk program manager

**Comment by femmerling** [comment]
Nama: Fauzan Emmerling
Email: erich@emfeld.com
Role: Sprints Manager

**Comment by vinamelody** [comment]
Nama: Vina Rianti
Email: vinamelody&#64;gmail.com
Role: English translation, flexible ...

Note: Posisi di Singapura, ada kenalan di PUSG / PyLadiesSG .. Engineers.sg for video recording of conferences (example [PyConSG 2016](https://engineers.sg/conference/pyconsg2016))

**Comment by RizRiyz** [comment]
Hi @vinamelody since you have good network and english skill, can you help handles communication with external parties, visa applications for attendees??

**Comment by alanugrohadi** [comment]
Nama: Alan Nugrohadi
Surel: alan.nugrohadi@gmail.com
Role: Venue Manager

**Comment by vinamelody** [comment]
@ariestiyansyah yup i can handle that :)

**Comment by fernandodaud** [comment]
Nama : Fernando daud
Email. : fernandodaud@ymail.com
Role.  : chair

**Comment by layumi3** [comment]
Nama : Lilis Ayumsari
Email : yumaim.lacorp@gmail.com
Role: External liason, outreach

**Comment by nsiregar** [comment]
Name : Ngalim Siregar
Email : ngalim.siregar@gmail.com
Role : Media Manager

**Comment by RizRiyz** [comment]
CLOSED!
