### ISSUE TITLE
Bikin blog post "Call For Volunteer" di blog Python ID

### ISSUE THREAD

**Issue by ariestiyansyah** [id-python/pycon-2017#3]
cc as original owner of the card @edwinlunando

**Comment by RizRiyz** [comment]
Sebagai Volunteer di PyCon Indonesia apa yang Kamu dapatkan?
- Exclusive staff-only t-shirt
- Bertemu dengan orang-orang Python 

Bantuan yang kami butuhkan?
- Proses registrasi
- Administrasi 
- Host
- Koordinasi Peserta
- Bantu memberikan micrphone pada saat Q&A

Apa yang Kami harapkan?
- Hadir tepat waktu pada saat acara

Bagaimana Mendaftar?
Sign up form

Please advise

**Comment by edwinlunando** [comment]
Boleh. Tak tulisin di blog python.or.id ya

**Comment by edwinlunando** [comment]
Bikin PR di GitHub buat daftar panitia aja gitu ya? Nanti bikin file daftar panitia. Sign up GDocs standar juga oke.

**Comment by RizRiyz** [comment]
@edwinlunando sign up form segera menyusul nanti dibuatkan menggunakan gdocs aja, btw kontentnya masih belum final ya
